import React, { useState } from 'react';
import { Modal } from 'react-bootstrap';
import { getHeroDetails } from '../../api/overfast';
import { capitalize } from '../../utils/playerStats';

export default function Hero({ hero }) {
  const [show,setShow]=useState(false), [details,setDetails]=useState(null), [status,setStatus]=useState('idle');
  const open=()=>{ setShow(true); if(details || status==='loading') return; setStatus('loading'); getHeroDetails(hero.key).then(data=>{setDetails(data);setStatus('ready')}).catch(()=>setStatus('error')); };
  const story=details?.story;
  return <><button className="hero-browser-card" onClick={open}><img src={hero.portrait} alt=""/><div><span>{capitalize(hero.role)}</span><h2>{hero.name}</h2><p>{hero.description || 'Open hero profile'}</p></div></button><Modal show={show} onHide={()=>setShow(false)} size="lg" centered scrollable dialogClassName="hero-modal"><Modal.Header closeButton><Modal.Title>{hero.name}</Modal.Title></Modal.Header><Modal.Body>{status==='loading' && <div className="modal-skeleton"><div className="skeleton hero-detail"/><div className="skeleton heroes"/></div>}{status==='error' && <p className="empty-state panel">This hero profile could not be loaded.</p>}{details && <><header className="hero-detail-header"><img src={details.portrait || hero.portrait} alt=""/><div><span className="scope-badge">{capitalize(details.role || hero.role)}</span><h2>{details.name || hero.name}</h2><p>{details.description}</p>{details.location && <strong>Base of operations: {details.location}</strong>}</div></header>{details.abilities?.length>0 && <section><div className="section-heading"><h3>Abilities</h3></div><div className="ability-grid">{details.abilities.map((ability,index)=><article key={ability.name || index}>{ability.icon && <img src={ability.icon} alt=""/>}<div><h4>{ability.name}</h4><p>{ability.description}</p></div></article>)}</div></section>}{story && <section className="story"><div className="section-heading"><h3>Story</h3></div>{story.summary && <p className="story-summary">{story.summary}</p>}{story.chapters?.map((chapter,index)=><article key={`${chapter.title || 'chapter'}-${index}`}>{chapter.picture && <img src={chapter.picture} alt=""/>}<div>{chapter.title && <h4>{chapter.title}</h4>}<p>{chapter.content || chapter.text || chapter.summary}</p></div></article>)}</section>}</>}</Modal.Body></Modal></>;
}
